"use strict";
const assert=require('assert/strict'),fs=require('fs'),path=require('path');
const code=fs.readFileSync(path.resolve(__dirname,'../overlay.html'),'utf8').split('<script>')[1].split('</script>')[0];
let texts=[];const handlers={},els={};
const ctx=new Proxy({measureText:()=>({width:100}),fillText:t=>texts.push(t),clearRect:()=>{texts=[];}},{get:(t,k)=>t[k]||(()=>{})});
const canvas={getContext:()=>ctx};
const doc={getElementById:id=>id==='c'?canvas:(els[id]||=( {style:{},textContent:''}))};
new Function('document','ad','addEventListener','innerWidth','innerHeight','setTimeout','clearTimeout',code)(doc,{on:(k,f)=>handlers[k]=f},()=>{},1920,864,()=>1,()=>{});
const active={phase:'active',current:{side:'L',idx:0},me:{side:'L',idx:0},playerScores:Array.from({length:10},(_,i)=>({box:[0,100+i*20,280,26],total:i===9?null:.82,heroKnown:true,skillCount:2,unknown:i===9?1:0}))};
handlers.cfg({scale:1,hidden:false});handlers.state(active);
assert.equal(texts.filter(t=>t.startsWith('组合')).length,10,'scores before advice');
assert.ok(texts.some(t=>t.includes('待识别')&&t.includes('—')));
handlers.computing({});assert.equal(texts.length,10,'independent of recommendation computation');
handlers.clear();assert.equal(texts.length,10,'recommendation clear keeps final draft scores');
handlers.cfg({scale:1,hidden:true});assert.equal(texts.length,0);
handlers.state(active);assert.equal(texts.length,0);
handlers.cfg({scale:1,hidden:false});assert.equal(texts.length,10);
handlers.state({...active,playerScores:active.playerScores.map(p=>({...p,total:1.23}))});
assert.ok(texts.every(t=>t.includes('+1.23')),'state-only correction redraws');
handlers.state({phase:'idle',idle:true,board:false});assert.equal(texts.length,0);
console.log('PASS scoreboard overlay: all seats, pre-advice, computing, clear, hidden, correction, idle');
